### ISSUE TITLE
looking for `from focal_loss import SparseCategoricalFocalLoss` code

### ISSUE THREAD

**Issue by monajalal** [farhantandia/Tricks-for-Handling-Imbalanced-Dataset-Image-Classification#1]
Hi Farhan,
Thanks a lot for the great open-source contribution in GitHub and also a great accompanying article on LinkedIn.

Where is the code for focal loss? Also how about using focal loss for an imbalanced binary classification problem?

`from focal_loss import SparseCategoricalFocalLoss`

**Comment by farhantandia** [comment]
Hi,
I used this package in my notebook https://pypi.org/project/focal-loss/ , For Binary classification you can import binary_focal_loss function. Thank you.
Br, 
Farhan
